### PR TITLE
(chore) update packages to resolve security vulnerabilities

### PR DESCRIPTION
**Pull request by bstahlhood**
Updating packages to help resolve the numerous security vulnerabilities reported by `npm i`

### CODE REVIEW

**Comment by nanov** [comment]
Thank you very much for your contribution. However your updates seem to drop support for older node versions.

@adrai Maybe it is time to drop support for Node < 6 ?

**Comment by adrai** [comment]
@nanov this is strange... 
image

**Comment by adrai** [comment]
@nanov just picked this: https://github.com/adrai/node-eventstore/commit/320034a7d55a17b72f68307db9755c0cb2683fc4

**Comment by nanov** [comment]
@adrai I think it was a honest mistake, he probably is maintaining a fork for his own needs.

**Pull request closed without merging**
