### PR TITLE
adding dynamodb store implementation

### PR DESCRIPTION
**Pull request by developmentalmadness**
DynamoDB tests can be run against a [local DynamoDB instance](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) and by making sure that the following environment variables are set:

    AWS_ACCESS_KEY_ID=anything_you_like
    AWS_SECRET_ACCESS_KEY=anything-you-like
    AWS_REGION=doesnt-matter-4-local
    AWS_DYNAMODB_ENDPOINT=http://localhost:8000

The first three values are arbitrary unless you want to connect to an existing AWS account the last one is required to point to the host:port combination of where you're running DynamoDB local.

If you want to connect to an existing AWS account, make sure the first 3 variables are properly set and the fourth one (`AWS_DYNAMODB_ENDPOINT`) doesn't exist.

I use DynamoDB local for development and then AWS for good measure. Running against a live account allows you to check for throttling issues (no throttling on DynamoDB local).

### CODE REVIEW

**Comment by adrai** [comment]
Woow!
May I ask why or for what you use dgnamodb support?
You have some TODO statements... Should we wait for a merge?
thx

**Comment by developmentalmadness** [comment]
It's for a project using AWS Lambda. I've used Johnathan Oliver's project since it was beta so I'm really comfortable with it. The fact that there's an established test suite really made your version attractive.

The TODO statements are more for polish and possible performance improvements. The current implementation is very solid - it'll run against DynamoDB with read/write capacities only at 1. It takes about 22 minutes for the test suite to run if the tests don't hit the 20 second timeout so I wouldn't recommend it. That said, I'm confident in the current implementation. I have to finish some other tasks before I come around and clean it all up though. I'll leave it up to you. If you prefer to put it on a feature branch of some kind until I come back around that's fine.

**Comment by developmentalmadness** [comment]
BTW, the reason the tests take so long when constrained is because of the `clear` code - it requires scanning the table and then batchWriteItem calls. Both use up a lot of resources but since they are being used only to run tests I don't think adding indexes to the schema is a good idea since they'll end up in production.

I tried to delete/create table instead but it takes a while to delete and allocate a new table after each test and caused more timeouts than the scans.

**Comment by adrai** [comment]
Ok… I think I will merge it… but I will not immediately publish a new version…

Am 04.08.2016 um 21:44 schrieb Mark J Miller <notifications@github.com<mailto:notifications@github.com>>:


It's for a project using AWS Lambda. I've used Johnathan Oliver's project since it was beta so I'm really comfortable with it. The fact that there's an established test suite really made your version attractive.

The TODO statements are more for polish and possible performance improvements. The current implementation is very solid - it'll run against DynamoDB with read/write capacities only at 1. It takes about 22 minutes for the test suite to run if the tests don't hit the 20 second timeout so I wouldn't recommend it. That said, I'm confident in the current implementation. I have to finish some other tasks before I come around and clean it all up though. I'll leave it up to you. If you prefer to put it on a feature branch of some kind until I come back around that's fine.

**Pull request merged**
