### PR TITLE
Feature/emit eventstore events

### PR DESCRIPTION
**Pull request by DaNautilus**
Emit nodejs events before and after an eventstore event including timestamp.

### CODE REVIEW

**Comment by nanov** [comment]
Hi @DaNautilus it seems you have done a pretty good job encapsulating this functionally into a separated module that wraps each the original store implementation.

Is there a real need for that to be enabled by default ( ie lines 75,76 in index.js ), and for it to be a part from this library? What is the exact use case of this?

**Comment by nanov** [comment]
I am waiting for the comments of @DaNautilus before taking further actions.
Without going into implementation details, i would leave this as optional add-on ( still can be a part of the library ) instead of enabling it by default.

**Comment by DaNautilus** [comment]
@nanov To support out maintenance we'd like to measure database events. Our cloud provider does not provide any database metrics and that's why we have to do it manually.

@adrai did it already for our denormalizers [node-viewmodel](https://github.com/adrai/node-viewmodel/pull/70). But unfortunately we miss this feature for our eventstore.

And yes, you're right we don't have to enable it by default. I'm going to implement a solution for that.

**Comment by nanov** [comment]
Great!

I am going to review, merge and release this later on today!

**Comment by nanov** [comment]
Landed in v1.15.0.

**Comment by DaNautilus** [comment]
Great, thanks a lot 👍🏻 🎉

**Pull request merged**
